### ISSUE TITLE
Add parameters and support for commands to select units

### ISSUE THREAD

**Issue by drodil** [drodil/rustybeer#10]
We need global parameters to select whether to use imperial or metric units for:

* Temperature (C/F/K)
* Weight (g, Kg, Oz...)
* Volume (l, gallon...)

For all of these we should provide different parameter in the main program parameters. Additionally a conversion tool that can be used should be in place for the sub-commands to use.

**Comment by mlatief** [comment]
how about one of two mutually exclusive flags `--metric` or `--imperial`, and default to `metric` for instance.

**Comment by drodil** [comment]
Sure might be shortcuts but then again someone needs to add for example grams in to play and if we use metric system the default is kilogram. But yeah, metric/imperial should be enough to start with.

**Comment by mlatief** [comment]
could it be some parser for units abbreviations as part of the input, something like `10g` or `0.1kg` and so on? the only problem it might be ambiguous for some units (I wonder if there's some standard abbreviations for imperial/metric units!)

**Comment by drodil** [comment]
Good idea! There is standard abbreviations for the units and we could use those. The only problem is that all subcommands need to get the parameters as string and then pass to the parser which would then return the value in SI unit or exit if it's an invalid one. This would affect to all commands but I think first we would need the parser implementation and even some unit tests (?).
