### ISSUE TITLE
Add dilution calculator

### ISSUE THREAD

**Issue by drodil** [drodil/rustybeer#13]
We need a dilution calculator to calculate how much you need to dilute your wort volume to hit a certain gravity. Parameters are volume of the wort, current gravity and target volume. The output shall be the the new gravity as well as the difference. Calculation is:

new gravity = (current gravity-1) * (current volume / target volume)

**Comment by ProgrammerJoe93** [comment]
I guess the 1 will need to be added back again at the end?
`new gravity = ((current gravity-1) * (current volume / target volume)) + 1`
