### ISSUE TITLE
Remove app_subcommand.rs

### ISSUE THREAD

**Issue by flauntingspade4** [drodil/rustybeer#29]
The trait defined in app_subcommand.rs (AppSubCommand) is never implemented, and redefined in main.rs
The only thing in app_subcommand.rs is the trait itself-if the trait is ever used in any way, it could be put in lib.rs, and app_subcommand.rs itself removed

**Comment by drodil** [comment]
Actually the AppSubCommand is implemented for all structs in the commands mod. For library this is not needed at all as the lib is only made to have all calculators and utilities available for other projects (such as rustybeer-aws-lambda). 

We're a bit rusty in rust (pun intended) so not actually sure if removing it would work. If you can do it without breaking the library and executable, please feel free to create PR :)

**Comment by drodil** [comment]
Oh damn you are right. Forgot it to main.rs. That actually can be removed!

**Comment by flauntingspade4** [comment]
I'm currently writing a fork to update futures to it's latest version, and add some very basic testing, should I include it in that?

**Comment by flauntingspade4** [comment]
I'm currently writing a fork to update futures to it's latest version, and add some very basic testing, should I include it in that?

**Comment by drodil** [comment]
Sure thing! Haven't done so much tests yet but they are more than welcome!

**Comment by drodil** [comment]
Done as dusted in #30
