### ISSUE TITLE
Why use futures?

### ISSUE THREAD

**Issue by flauntingspade4** [drodil/rustybeer#32]
This may be a stupid question, but why use the futures library? This doesn't seem like the kind of task that requires async programming, unless there's some requirement in the CLI app which I'm not aware of.
Would someone mind explaining to me why it's included?

**Comment by mlatief** [comment]
In the priming module, we ended up using streams to go through the list of Sugars (in case we would've read them from a file or some REST service). Nothing fancy really, not yet at least. Now thinking of it, it might have been an overkill for the task.

**Comment by flauntingspade4** [comment]
Ah, I thought it was something like that-yeah, in my for I've completely removed futures as a dependency, and just implemented it as a Vec instead.
Btw, I'm pretty sure the std::io::Read trait was implemented for that kind of task
