### ISSUE TITLE
Add hops support

### ISSUE THREAD

**Issue by drodil** [drodil/rustybeer#39]
To be able to use IBU calculator without need to set AA for all hops it would be beneficial to have most known hops in the app.  Create new struct for hop and define constant hops from https://www.brewersfriend.com/hops/ . Each hop should have name, average AA and aroma/bittering(boil)/whirlpool/dry hop (enum) usage information. 

Additionally create command to find hops based on their average AA with min and max values or with their usage type. 

See #23 as an example.

**Comment by mlatief** [comment]
This is a wip in #24, especially that AA is needed for IBU calculations

**Comment by drodil** [comment]
@mlatief great! Please still see details in this ticket so we can use the hops also to other functionalities later on..
