### ISSUE TITLE
Local database support

### ISSUE THREAD

**Issue by drodil** [drodil/rustybeer#43]
As it is very painful to keep the beer, hops and yeast data in Rust structs, find out if there is optional solution to store this data inside the executable/lib. For example file based database that could travel inside the package. See #23 #39 #41 #42 for use cases of this.

**Comment by tommilligan** [comment]
Personally, I would just add data files in JSON/YAML format and load them when required with `serde`.

Pros:
- easily editable/contributable
- tiny amount of code required to load
- fits the existing data structures ([a big vec of data](https://github.com/drodil/rustybeer/pull/23/files#diff-d776592fbae3473bd63b6066d15ac444R191))

Cons:
- ~will take slightly longer to load all data data from disk than if we were querying data as needed from a proper database~ if we include it [as a string inline at compile time](https://stackoverflow.com/questions/25505275/is-there-a-good-way-to-include-external-resource-data-into-rust-source-code), it will just be the time to parse the string into a struct which is negligible.

If you think that's an okay solution, I'll start working on it.

**Comment by mlatief** [comment]
that sounds good actually, please go ahead.

**Comment by drodil** [comment]
Sounds like a good idea! Just wondering about the packaging of the json for the rustybeer library; is it possible to do somehow so that the users of the library have the same data available? Don't have that much of experience about that so please enlighten me! :)
