### ISSUE TITLE
Add missing documentation

### ISSUE THREAD

**Issue by drodil** [drodil/rustybeer#48]
Add missing documentation especially for the calculators. What are the expected inputs and in which unit is crucial information for the user of the library.

**Comment by flauntingspade4** [comment]
Ok, I'll have a go at writing some documentation

**Comment by flauntingspade4** [comment]
What's the difference between `calculators::boil_off` and `calculators::diluting`, other than that `calculators::diluting` is missing a method to calculate a new volume? While writing the documentation I noticed they seemed identical

**Comment by mlatief** [comment]
Very valid point. I can't see a difference myself. @drodil chime in?

**Comment by drodil** [comment]
Actually they don't have any difference. Diluting is adding more water to the batch to reach desired gravity (water amount goes up so gravity goes down) while boil-off is to remove water (water amount goes down so gravity goes up). So when doing boil-off, this calculator should return negative number indicating how much water should be removed by boiling. See a reference calculator here https://www.brewersfriend.com/dilution-and-boiloff-gravity-calculator/

**Comment by flauntingspade4** [comment]
I'm not 100% sure I follow, but if I understand correctly, we can just get rid of `calculators::boil_off::BoilOff`, and instead use `calculators::diluting::Diluting::calculate_new_volume` (I think is the correct method), and just negate, allowing us to remove `calculators::boil_off::BoilOff`?
