### ISSUE TITLE
Add calorie calculalator

### ISSUE THREAD

**Issue by drodil** [drodil/rustybeer#54]
Add calculator to calculate calories in beer serving of different sizes or by custom volume (100ml by default). Use calculation formula example from here http://www.brewunited.com/beer_calorie_calculator.php

The calculator should take parameters for ABV or original+final gravity (use AbvCalculator to calculate ABV from those). It should report calories for all custom values given for volumes and additionally for different serving sizes done as part of #35 

Calories should be reported in kcal and kJ per serving size. Additionally carbs amount would be interesting. 

Add also command to run this calculator from CLI

**Comment by rogercyyu** [comment]
Hello, can I try to tackle this?

**Comment by drodil** [comment]
@rogercyyu sure, go ahead!
